version: '3'
services:
  client:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5000
    depends_on:
      - api-gateway
      - pricer

  api-gateway:
    build: ./backend/api-gateway
    ports:
      - 5000:5000
    environment:
      - CLIENT_DOMAIN=localhost
      - CLIENT_URL=http://localhost:3000
      - PRICING_SERVICE_URL=htpp://localhost:34566
    depends_on:
      - redis-db

  pricer:
    build: ./backend/black-model-pricer
    ports:
      - 34566:34566

  redis-db:
    image: redis:latest
    volumes:
      - redis_data:/data
volumes:
  redis_data: